Grid schduling Simulation sequential: Island Class Reference
Island Class Reference
#include <island.h>
Public Member Functions
Island (int populationSize, int popInitMethod, int fitnessType, int myrank)
~Island ()
void setTaskMiRatings (vector< double > miRatings)
vector< double > getTaskMiRatings ()
vector< Schedule > migrate (vector< Schedule > aPopulation)
Schedule runGA (ResourceList resourceList, vector< double > miRequirements)
void outputData ()
int getIterations ()
double getFitness (Schedule aSchedule, int fitnessType)
void setMyRank (int rank)
int getMyRank ()
void setCommunicator (MPI_Comm communicator)
void setNeighbors (int left, int right)
double getT_init ()
double getT_comp ()
double getT_comm ()
double * getT_compGA ()
double getT_compFitnessEval ()
Private Member Functions
void randomInit ()
vector< double > getResourceMipsRatings ()
vector< double > getResourceLoads ()
void taskMi2fastest (int option)
void timeStart ()
void timeEnd (int what)
Private Attributes
int batchSize
int populationSize
int popInitMethod
int fitnessType
vector< double > resourceMipsRatings
vector< double > resourceLoads
ResourceList resourceList
vector< double > taskMiRatings
vector< Schedule > population
GeneticAlgorithm * ga
int randomIndex
int numOfResources
ofstream output
int width
int iterations
double flowTime
double waitTime
double executionTime
int myrank
MPI_Comm communicator
int myLeft
int myRight
double sigma
double maxdif
double t_init
double t_comp
double t_comm
double t_compFitnessEval
double t_compGA [5]
double td
long sec
long usec
struct timeval tp
Detailed Description
This is a schduling implementation of the island model. Each islend holds sub-set of the population, in which it applyes a GA. This class has a migration operation to enable for mixing of populations/solution
Author:
S. Koulouzis, T. Wood <skoulouz@science.uva.nl>
Definition at line 32 of file island.h.
Constructor & Destructor Documentation
Island::Island (int populationSize, int popInitMethod, int fitnessType, int myrank)
An emty constructor, that will create an island.
Definition at line 22 of file island.cpp.
References ga, output, sec, t_comm, t_comp, t_compFitnessEval, t_compGA, t_init, td, usec, and width.
Island::~Island ()
Definition at line 610 of file island.cpp.
Member Function Documentation
void Island::setTaskMiRatings (vector< double > miRatings)
This method initializes the population in this island. In the parallel version the population is a sub-set of the global population (a //sub-set of solutions to evaluate). The batchSize sets the size of an individual schedule, that is used in initializing the population, and //running the GA, while the mipsRatings and miRequirements are ther to be used by the GA
Parameters:
int
int
ResourceList
vector<double> set the mpis rating of resources (a vector of doubles) for population initialization, and for the // fitness function in the GA
mipsRatings returns the mpis rating of resources seen by this island
Returns:
vector<double> set the mi rating of tasks (a vector of doubles) for population initialization, and for the fitness function in the GA
Parameters:
mipsRatings
Definition at line 147 of file island.cpp.
References batchSize, and taskMiRatings.
Referenced by runGA().
vector<double> Island::getTaskMiRatings ()
returns the mpis rating of tasks seen by this island
Returns:
vector<double>
vector< Schedule > Island::migrate (vector< Schedule > aPopulation)
After a sertant amount of iterations, the island is migrating some of its population to its neighbor. For MPI this sould be an array for esyer communication.
Parameters:
vector<Schedule>
Returns:
vector<Schedule>
Definition at line 448 of file island.cpp.
References batchSize, communicator, myLeft, myRight, and status.
Referenced by runGA().
Schedule Island::runGA (ResourceList resourceList, vector< double > miRequirements)
An MPI recive operation for reciving population from neighbor islands (acoarding to the MPI topology)
Returns:
vector<Schedule> This method starts running a genetic algorithm, based on the population created by the initialize method.After the GA is done it will return a "good" population, optimized by execution time, of size n. Make sure that the initialize method is called before calling this method.
Parameters:
int
Returns:
vector<Schedule>
end of init
end stopping cond stuff
Definition at line 182 of file island.cpp.
References GeneticAlgorithm::addIndividual(), batchSize, communicator, GeneticAlgorithm::crossover(), GeneticAlgorithm::fitnessFunction(), fitnessType, ga, GeneticAlgorithm::getAveragefitness(), GeneticAlgorithm::getBestSchedules(), GeneticAlgorithm::getPopulation(), getResourceLoads(), getResourceMipsRatings(), iterations, MAX_DOUBLE, maxdif, migrate(), GeneticAlgorithm::mutation(), GeneticAlgorithm::naturalSelection(), GeneticAlgorithm::parentsSelection(), popInitMethod, population, populationSize, randomInit(), GeneticAlgorithm::removeIndividuals(), resourceLoads, resourceMipsRatings, GeneticAlgorithm::setNumOfResources(), GeneticAlgorithm::setPopulation(), GeneticAlgorithm::setResourceMipsRatings(), GeneticAlgorithm::setResourcesLoad(), GeneticAlgorithm::setTaskMiRatings(), setTaskMiRatings(), sigma, taskMi2fastest(), timeEnd(), and timeStart().
Referenced by runSimulation().
void Island::outputData ()
Out puts data to a file
Definition at line 421 of file island.cpp.
References executionTime, flowTime, iterations, output, and waitTime.
int Island::getIterations ()
returns the number of iterations it took the GA to return a schedule
Returns:
int
Definition at line 417 of file island.cpp.
References iterations.
Referenced by getGaIterations().
double Island::getFitness (Schedule aSchedule, int fitnessType)
returns the fitness of a schedule specified by the fitnessType
Parameters:
Schedule
int
Returns:
double
Definition at line 431 of file island.cpp.
References GeneticAlgorithm::fitnessFunction(), and ga.
Referenced by getBestSchedules().
void Island::setMyRank (int rank)
sets the rank of this isleand. Only for island model use, with migration (MPI)
Parameters:
int
Definition at line 444 of file island.cpp.
References myrank.
int Island::getMyRank ()
retunts this iseland's rank. Only for island model use, with migration (MPI)
Returns:
int
void Island::setCommunicator (MPI_Comm communicator)
Sets the communicator of this island, so migration and stopping conditions may be used.
Parameters:
MPI_Comm
Definition at line 435 of file island.cpp.
Referenced by runSimulation().
void Island::setNeighbors (int left, int right)
Sets the left and right neighbors for this iseland, in order to know where to migrate
Parameters:
int
int
Definition at line 439 of file island.cpp.
References myLeft, and myRight.
Referenced by runSimulation().
double Island::getT_init ()
returns the initilization time in sec
Returns:
double
Definition at line 590 of file island.cpp.
References t_init.
double Island::getT_comp ()
returns the computation time in sec
Returns:
double
Definition at line 594 of file island.cpp.
References t_comp.
double Island::getT_comm ()
returns the communication time in sec
Returns:
double
Definition at line 598 of file island.cpp.
References t_comm.
double * Island::getT_compGA ()
returns the comutation time of the GA in sec
Returns:
*double
Definition at line 602 of file island.cpp.
References t_compGA.
double Island::getT_compFitnessEval ()
returns the fitness evaluation time in sec
Returns:
double
Definition at line 606 of file island.cpp.
References t_compFitnessEval.
void Island::randomInit () [private]
Initializes the population randomly
Definition at line 56 of file island.cpp.
References batchSize, numOfResources, population, and populationSize.
Referenced by runGA().
vector< double > Island::getResourceMipsRatings () [private]
Returns a vector of doubles representing the mips ratings of the resources listed in resourceList.
Returns:
vector<double>
Definition at line 155 of file island.cpp.
References Gresource::mips, numOfResources, and resourceList.
Referenced by runGA().
vector< double > Island::getResourceLoads () [private]
Returns a vectorof doubles representing the current loads of the resources listed in resourceList...
Returns:
vector<double>
Definition at line 167 of file island.cpp.
References Gresource::load, resourceList, and resourceLoads.
Referenced by runGA().
void Island::taskMi2fastest (int option) [private]
Allocate tasks to resources depending on task requirements Tasks are either assigned to task by shortest task to fastest resource or if 'option' is set to '1' longest taskto fastest resource...
Parameters:
int
Allocate tasks to resources depending on task requirements
Tasks are either assigned to task by shortest task to fastest resource or if 'option' is set to '1' longest taskto fastest resource...
Definition at line 75 of file island.cpp.
References batchSize, numOfResources, population, populationSize, resourceMipsRatings, and taskMiRatings.
Referenced by runGA().
void Island::timeStart () [private]
Starts counting time
Definition at line 508 of file island.cpp.
References myrank, sec, tp, and usec.
Referenced by runGA().
void Island::timeEnd (int what) [private]
Stops counting time, could it is communication, computation etc.
Parameters:
int
Definition at line 525 of file island.cpp.
References myrank, sec, t_comm, t_comp, t_compFitnessEval, t_compGA, t_init, td, tp, and usec.
Referenced by runGA().
Member Data Documentation
int Island::batchSize [private]
Definition at line 217 of file island.h.
Referenced by migrate(), randomInit(), runGA(), setTaskMiRatings(), and taskMi2fastest().
int Island::populationSize [private]
Definition at line 218 of file island.h.
Referenced by randomInit(), runGA(), and taskMi2fastest().
int Island::popInitMethod [private]
Definition at line 218 of file island.h.
Referenced by runGA().
int Island::fitnessType [private]
Definition at line 218 of file island.h.
Referenced by runGA().
vector<double> Island::resourceMipsRatings [private]
Definition at line 219 of file island.h.
Referenced by runGA(), and taskMi2fastest().
vector<double> Island::resourceLoads [private]
Definition at line 220 of file island.h.
Referenced by getResourceLoads(), and runGA().
ResourceList Island::resourceList [private]
Definition at line 221 of file island.h.
Referenced by getResourceLoads(), and getResourceMipsRatings().
vector<double> Island::taskMiRatings [private]
Definition at line 222 of file island.h.
Referenced by setTaskMiRatings(), and taskMi2fastest().
vector<Schedule> Island::population [private]
Definition at line 223 of file island.h.
Referenced by randomInit(), runGA(), and taskMi2fastest().
GeneticAlgorithm* Island::ga [private]
Definition at line 224 of file island.h.
Referenced by getFitness(), Island(), and runGA().
int Island::randomIndex [private]
Definition at line 225 of file island.h.
int Island::numOfResources [private]
Definition at line 226 of file island.h.
Referenced by getResourceMipsRatings(), randomInit(), and taskMi2fastest().
ofstream Island::output [private]
Definition at line 227 of file island.h.
Referenced by Island(), and outputData().
int Island::width [private]
Definition at line 228 of file island.h.
Referenced by Island().
int Island::iterations [private]
Definition at line 229 of file island.h.
Referenced by getIterations(), outputData(), and runGA().
double Island::flowTime [private]
Definition at line 230 of file island.h.
Referenced by outputData().
double Island::waitTime [private]
Definition at line 230 of file island.h.
Referenced by outputData().
double Island::executionTime [private]
Definition at line 231 of file island.h.
Referenced by outputData().
int Island::myrank [private]
Definition at line 233 of file island.h.
Referenced by setMyRank(), timeEnd(), and timeStart().
MPI_Comm Island::communicator [private]
Definition at line 234 of file island.h.
Referenced by migrate(), and runGA().
int Island::myLeft [private]
Definition at line 235 of file island.h.
Referenced by migrate(), and setNeighbors().
int Island::myRight [private]
Definition at line 235 of file island.h.
Referenced by migrate(), and setNeighbors().
double Island::sigma [private]
Definition at line 236 of file island.h.
Referenced by runGA().
double Island::maxdif [private]
Definition at line 237 of file island.h.
Referenced by runGA().
double Island::t_init [private]
Definition at line 238 of file island.h.
Referenced by getT_init(), Island(), and timeEnd().
double Island::t_comp [private]
Definition at line 239 of file island.h.
Referenced by getT_comp(), Island(), and timeEnd().
double Island::t_comm [private]
Definition at line 240 of file island.h.
Referenced by getT_comm(), Island(), and timeEnd().
double Island::t_compFitnessEval [private]
Definition at line 241 of file island.h.
Referenced by getT_compFitnessEval(), Island(), and timeEnd().
double Island::t_compGA[5] [private]
Definition at line 242 of file island.h.
Referenced by getT_compGA(), Island(), and timeEnd().
double Island::td [private]
Definition at line 243 of file island.h.
Referenced by Island(), and timeEnd().
long Island::sec [private]
Definition at line 244 of file island.h.
Referenced by Island(), timeEnd(), and timeStart().
long Island::usec [private]
Definition at line 244 of file island.h.
Referenced by Island(), timeEnd(), and timeStart().
struct timeval Island::tp [read, private]
Definition at line 245 of file island.h.
Referenced by timeEnd(), and timeStart().
The documentation for this class was generated from the following files:
UvA Files/Distributed Stochastic Simulation/Grid_Scheduling_Wood_Koulouzis/src/scheduler_MPI/island.h
UvA Files/Distributed Stochastic Simulation/Grid_Scheduling_Wood_Koulouzis/src/scheduler_MPI/island.cpp