Grid schduling Simulation sequential: GeneticAlgorithm Class Reference
GeneticAlgorithm Class Reference
#include <geneticalgorithm.h>
Public Member Functions
GeneticAlgorithm (vector< Schedule > aPopulation)
GeneticAlgorithm ()
~GeneticAlgorithm ()
vector< Schedule > parentsSelection (int kindOfSelection)
void naturalSelection (vector< Schedule > candidates, int kindOfFitness)
void rouletteWheelSelection (vector< Schedule > candidates, int kindOfFitness)
vector< Schedule > crossover (vector< Schedule > parents, int kindOfXover)
Schedule mutation (Schedule aSchedule, double rateOfMutation)
Schedule mutationWithHeuristic (Schedule aSchedule, double rateOfMutation)
double fitnessFunction (Schedule aSchedule, int kindOfFitness)
double getAveragefitness (int kindOfFitness)
void setPopulation (vector< Schedule > aPopulation)
vector< Schedule > getPopulation ()
int getNumOfResources ()
void setNumOfResources (int num)
void setResourceMipsRatings (vector< double > mipsRatings)
vector< double > getResourceMipsRatings ()
void setTaskMiRatings (vector< double > miRatings)
vector< double > getTaskMiRatings ()
void setResourcesLoad (vector< double > resourcesLoad)
vector< double > getResourcesLoad ()
vector< Schedule > getBestSchedules (int n, int kinOfFitness)
vector< int > getIndexOfBestSchedules (int n, int kinOfFitness)
void removeIndividuals (int n)
void addIndividual (Schedule aSchedule)
void removeIndividualsByIndex (int index)
Private Member Functions
vector< Schedule > randomParentsSelection ()
vector< Schedule > onePointscrossover (vector< Schedule > parents)
double executionTimeFunction (Schedule aSchedule)
double flowTimeFunction (Schedule aSchedule)
double getWaitTimeFunction (Schedule aSchedule)
double resourceUtilizationFunction (Schedule aSchedule)
Private Attributes
vector< Schedule > population
vector< Schedule > orderedPopulation
int randomIndex
double randomNum
vector< double > resourceMipsRatings
vector< double > taskMiRatings
vector< double > resourcesLoad
double executionTime
double waitTime
double mi
double mips
double resLoad
int numOfResources
Detailed Description
This is a genetic algorithm imlementation. It provides all the operations of a GA like selection, mutation etc
Author:
S. Koulouzis, T. Wood <skoulouz@science.uva.nl>
Definition at line 33 of file geneticalgorithm.h.
Constructor & Destructor Documentation
GeneticAlgorithm::GeneticAlgorithm (vector< Schedule > aPopulation)
Constructor of the GA
Parameters:
vector<Schedule>
Definition at line 22 of file geneticalgorithm.cpp.
References population.
GeneticAlgorithm::GeneticAlgorithm ()
Definition at line 26 of file geneticalgorithm.cpp.
GeneticAlgorithm::~GeneticAlgorithm ()
Definition at line 428 of file geneticalgorithm.cpp.
Member Function Documentation
vector< Schedule > GeneticAlgorithm::parentsSelection (int kindOfSelection)
Selects 2 parents for the first step of the GA, taken from the population. The selection might be random,or according to some heuristic. If the selection is a tournament selection then this operation should select a sub set of the population, and return the 2 best. The different kinds of selection are specified according the kindOfSelection int Note this operation reruns only 2 parents.
Returns:
vector<Schedule>
Parameters:
kindOfSelection
Definition at line 30 of file geneticalgorithm.cpp.
References randomParentsSelection().
Referenced by Island::runGA().
void GeneticAlgorithm::naturalSelection (vector< Schedule > candidates, int kindOfFitness)
It takes a vector of schedules, and eliminates the "weak" ones, by calculating their fitness, which is selected acoarding to the
Parameters:
int. This method should keep the population size constant
candidates
int
Definition at line 270 of file geneticalgorithm.cpp.
References fitnessFunction(), MAX_INT, MIN_INT, and population.
Referenced by Island::runGA().
void GeneticAlgorithm::rouletteWheelSelection (vector< Schedule > candidates, int kindOfFitness)
It takes candidates, and evaluates their fitness. So better individuals get higher chance of not being eliminted. Chances proportional to fitness. Assign to each individual a part of the roulette wheel,spin the wheel n times to select n individuals. This method should keep the population size constant
Parameters:
candidates
int
vector< Schedule > GeneticAlgorithm::crossover (vector< Schedule > parents, int kindOfXover)
This is a corossover between 2 parrents. The crossover might be random, cyclic, or any other kind. The kind of crossover is determined by kindOfXover It returns 2 new offsprings
Returns:
vector<Schedule>
Parameters:
parents
kindOfXover
Definition at line 62 of file geneticalgorithm.cpp.
References onePointscrossover().
Referenced by Island::runGA().
Schedule GeneticAlgorithm::mutation (Schedule aSchedule, double rateOfMutation)
Takes an individual as an input, mutates it, and reurns it. The mutation migth be swaping geens from a random, schedule/individual or random change from a resource list. Alter each gene independently with a probability pm pm is called the mutation rate, typically between 1/pop_size and 1/ chromosome_length
Returns:
Schedule
Parameters:
aSchedule
rateOfMutation
Definition at line 124 of file geneticalgorithm.cpp.
References numOfResources, and randomIndex.
Referenced by Island::runGA().
Schedule GeneticAlgorithm::mutationWithHeuristic (Schedule aSchedule, double rateOfMutation)
Definition at line 147 of file geneticalgorithm.cpp.
References numOfResources, and randomIndex.
double GeneticAlgorithm::fitnessFunction (Schedule aSchedule, int kindOfFitness)
it reurns the fitness of an individual, acoarding what needs to be measured
Returns:
double
Parameters:
aSchedule
kindOfFitness
Definition at line 172 of file geneticalgorithm.cpp.
References executionTime, executionTimeFunction(), flowTimeFunction(), and getWaitTimeFunction().
Referenced by getAveragefitness(), Island::getFitness(), naturalSelection(), and Island::runGA().
double GeneticAlgorithm::getAveragefitness (int kindOfFitness)
returns the average fitness of the GA's population, according to a specified fitness function
Parameters:
double
Returns:
double
Definition at line 304 of file geneticalgorithm.cpp.
References fitnessFunction(), and population.
Referenced by Island::runGA().
void GeneticAlgorithm::setPopulation (vector< Schedule > aPopulation)
set the initial population for this GA.
Parameters:
vector<Schedule>
Definition at line 318 of file geneticalgorithm.cpp.
References population.
Referenced by Island::runGA().
vector< Schedule > GeneticAlgorithm::getPopulation ()
get The current population
Returns:
vector<Schedule>
Definition at line 314 of file geneticalgorithm.cpp.
References population.
Referenced by Island::runGA().
int GeneticAlgorithm::getNumOfResources ()
returns the number of resources seen by this GA
Returns:
int
void GeneticAlgorithm::setNumOfResources (int num)
sets the number of resources to this GA. It is used in mutation, to swap a geen(resource id) in a schedule,with a random resource.
Parameters:
int
Definition at line 322 of file geneticalgorithm.cpp.
References numOfResources.
Referenced by Island::runGA().
void GeneticAlgorithm::setResourceMipsRatings (vector< double > mipsRatings)
set the mpis rating of resources (a vector of doubles) for use in the fitness function
Parameters:
mipsRatings
Definition at line 326 of file geneticalgorithm.cpp.
References resourceMipsRatings.
Referenced by Island::runGA().
vector< double > GeneticAlgorithm::getResourceMipsRatings ()
returns the mpis rating of resources seen by this GA
Returns:
vector<double>
Definition at line 330 of file geneticalgorithm.cpp.
References resourceMipsRatings.
void GeneticAlgorithm::setTaskMiRatings (vector< double > miRatings)
set the mi rating of tasks (a vector of doubles) for use in the fitness function
Parameters:
mipsRatings
Definition at line 334 of file geneticalgorithm.cpp.
References taskMiRatings.
Referenced by Island::runGA().
vector< double > GeneticAlgorithm::getTaskMiRatings ()
returns the mpis rating of tasks seen by this GA
Returns:
vector<double>
Definition at line 338 of file geneticalgorithm.cpp.
References taskMiRatings.
void GeneticAlgorithm::setResourcesLoad (vector< double > resourcesLoad)
set the mi rating of tasks (a vector of doubles) for use in the fitness function
Parameters:
mipsRatings
Definition at line 342 of file geneticalgorithm.cpp.
Referenced by Island::runGA().
vector< double > GeneticAlgorithm::getResourcesLoad ()
returns the mpis rating of tasks seen by this GA
Returns:
vector<double>
Definition at line 346 of file geneticalgorithm.cpp.
References resourcesLoad.
vector< Schedule > GeneticAlgorithm::getBestSchedules (int n, int kinOfFitness)
returns n best schedules, ordered by their fitness, which is specified by the kinOfFitness parameter.
Parameters:
int
int
Returns:
vector<Schedule>
Definition at line 350 of file geneticalgorithm.cpp.
References orderedPopulation, and population.
Referenced by Island::runGA().
vector< int > GeneticAlgorithm::getIndexOfBestSchedules (int n, int kinOfFitness)
returns the n best schedule's indexs, ordered by their fitness, which is specified by the kinOfFitness parameter.
Parameters:
int
int
Returns:
vector<int>
Definition at line 383 of file geneticalgorithm.cpp.
References population.
void GeneticAlgorithm::removeIndividuals (int n)
removes n individuals from the GA's population
Parameters:
int
Definition at line 416 of file geneticalgorithm.cpp.
References population.
Referenced by Island::runGA().
void GeneticAlgorithm::addIndividual (Schedule aSchedule)
Adds an individual to tha GA's population
Parameters:
Schedule
Definition at line 424 of file geneticalgorithm.cpp.
References population.
Referenced by Island::runGA().
void GeneticAlgorithm::removeIndividualsByIndex (int index)
removes an individual from the GA's population according to its index
Parameters:
int
Definition at line 410 of file geneticalgorithm.cpp.
References population.
vector< Schedule > GeneticAlgorithm::randomParentsSelection () [private]
Random selection. It takes 2 random int and chooses the parent according to those
Returns:
vector<Schedule>
Definition at line 47 of file geneticalgorithm.cpp.
References population, and randomIndex.
Referenced by parentsSelection().
vector< Schedule > GeneticAlgorithm::onePointscrossover (vector< Schedule > parents) [private]
1-point crossover. Choose a random point on the two parents Split parents at this crossover point Create children by exchanging tails
Parameters:
vector<Schedule>
Returns:
vector<Schedule>
Definition at line 77 of file geneticalgorithm.cpp.
References randomIndex.
Referenced by crossover().
double GeneticAlgorithm::executionTimeFunction (Schedule aSchedule) [private]
calculates the total execution time of a schedule
Parameters:
Schedule
Returns:
double
This function returns the execution time only
Definition at line 198 of file geneticalgorithm.cpp.
References executionTime, mi, mips, resourceMipsRatings, and taskMiRatings.
Referenced by fitnessFunction().
double GeneticAlgorithm::flowTimeFunction (Schedule aSchedule) [private]
calculates the total flow time of a schedule
Parameters:
Schedule
Returns:
double
Definition at line 218 of file geneticalgorithm.cpp.
References executionTime, mi, mips, resLoad, resourceMipsRatings, resourcesLoad, taskMiRatings, and waitTime.
Referenced by fitnessFunction().
double GeneticAlgorithm::getWaitTimeFunction (Schedule aSchedule) [private]
calculates the total wait time of a schedule, taking the load of resources
Parameters:
Schedule
Returns:
double
this function returns the waittime only, for a schedule
Definition at line 245 of file geneticalgorithm.cpp.
References mips, resLoad, resourceMipsRatings, resourcesLoad, and waitTime.
Referenced by fitnessFunction().
double GeneticAlgorithm::resourceUtilizationFunction (Schedule aSchedule) [private]
calculates the resource Utilization of a schedule
Parameters:
Schedule
Returns:
double
Member Data Documentation
vector<Schedule> GeneticAlgorithm::population [private]
Definition at line 252 of file geneticalgorithm.h.
Referenced by addIndividual(), GeneticAlgorithm(), getAveragefitness(), getBestSchedules(), getIndexOfBestSchedules(), getPopulation(), naturalSelection(), randomParentsSelection(), removeIndividuals(), removeIndividualsByIndex(), and setPopulation().
vector<Schedule> GeneticAlgorithm::orderedPopulation [private]
Definition at line 253 of file geneticalgorithm.h.
Referenced by getBestSchedules().
int GeneticAlgorithm::randomIndex [private]
Definition at line 254 of file geneticalgorithm.h.
Referenced by mutation(), mutationWithHeuristic(), onePointscrossover(), and randomParentsSelection().
double GeneticAlgorithm::randomNum [private]
Definition at line 255 of file geneticalgorithm.h.
vector<double> GeneticAlgorithm::resourceMipsRatings [private]
Definition at line 256 of file geneticalgorithm.h.
Referenced by executionTimeFunction(), flowTimeFunction(), getResourceMipsRatings(), getWaitTimeFunction(), and setResourceMipsRatings().
vector<double> GeneticAlgorithm::taskMiRatings [private]
Definition at line 257 of file geneticalgorithm.h.
Referenced by executionTimeFunction(), flowTimeFunction(), getTaskMiRatings(), and setTaskMiRatings().
vector<double> GeneticAlgorithm::resourcesLoad [private]
Definition at line 258 of file geneticalgorithm.h.
Referenced by flowTimeFunction(), getResourcesLoad(), and getWaitTimeFunction().
double GeneticAlgorithm::executionTime [private]
Definition at line 260 of file geneticalgorithm.h.
Referenced by executionTimeFunction(), fitnessFunction(), and flowTimeFunction().
double GeneticAlgorithm::waitTime [private]
Definition at line 260 of file geneticalgorithm.h.
Referenced by flowTimeFunction(), and getWaitTimeFunction().
double GeneticAlgorithm::mi [private]
Definition at line 261 of file geneticalgorithm.h.
Referenced by executionTimeFunction(), and flowTimeFunction().
double GeneticAlgorithm::mips [private]
Definition at line 262 of file geneticalgorithm.h.
Referenced by executionTimeFunction(), flowTimeFunction(), and getWaitTimeFunction().
double GeneticAlgorithm::resLoad [private]
Definition at line 263 of file geneticalgorithm.h.
Referenced by flowTimeFunction(), and getWaitTimeFunction().
int GeneticAlgorithm::numOfResources [private]
This is used in mutation, where we need to swap on resource ID to an other. So the random number is from 0 to numOfResources
Definition at line 269 of file geneticalgorithm.h.
Referenced by mutation(), mutationWithHeuristic(), and setNumOfResources().
The documentation for this class was generated from the following files:
UvA Files/Distributed Stochastic Simulation/Grid_Scheduling_Wood_Koulouzis/src/scheduler_MPI/geneticalgorithm.h
UvA Files/Distributed Stochastic Simulation/Grid_Scheduling_Wood_Koulouzis/src/scheduler_MPI/geneticalgorithm.cpp